### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kurainu** [Ryochan7/DS4WindowsAPI#1]
Can you please Provide some Information or Readme on how to use your DS4WindowsAPI?
i was kinda toying around with it but didnt get it all to work properly

**Comment by Ryochan7** [comment]
Never saw this issue before now. There are no docs on how to use this project. It is not really meant for public consumption. The closest reference on using the library is an old test program I wrote a while back. The program used the DS4Library to enumerate DS4 controllers, read input reports for exposed controllers and then finally send the report to ScpVBus.

Main program file:
https://github.com/Ryochan7/WpfApp4/blob/master/WpfApp4/Tester.cs

Project:
https://github.com/Ryochan7/WpfApp4

**Comment by Kurainu** [comment]
Closing this Issue now . i completly Forgot about it.
